name: step env duplicate
on:
  workflow_dispatch:

jobs:
  step-env-duplicate:
    permissions: {}
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    steps:
      - run: foo "$FOOBAR"
        env:
          FOOBAR: "foobar"
        env:
          PIYOPIYO: "piyopiyo"
