name: uses-and-run

on:
  push:

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: checkout and run
        uses: actions/checkout@v4
        run: echo "done"
