<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Seiton.Playground</RootNamespace>
    <AssemblyName>Seiton.Playground.Core</AssemblyName>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Seiton.Core\Seiton.Core.csproj" />
  </ItemGroup>

</Project>
