using System.Text;

namespace Seiton.Update.Generators;

internal class GeneratorHelper
{
    internal static void AppendGeneratedHeader(StringBuilder sb, string command)
    {
        sb.AppendLine("#nullable enable");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This file is generated by Seiton.Update. Do not edit manually.");
        sb.AppendLine($"// Regenerate: dotnet run --project src/Seiton.Update -- {command}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
    }
}
