using System.Text;
using Seiton.Update.Model;

namespace Seiton.Update.Generators;

internal sealed class PermissionsCSharpGenerator
{
    public string Generate(PermissionsModel model)
    {
        var scopes = model.Scopes
            .OrderBy(static s => s.Name, StringComparer.Ordinal)
            .ToArray();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// To regenerate this file, run:");
        sb.AppendLine("//   dotnet run --project src/Seiton.Update -- sync-permissions");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("namespace Seiton.Core.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class PermissionScopes");
        sb.AppendLine("{");

        // AllScopeNames array
        sb.AppendLine("    /// <summary>All known permission scope names, sorted alphabetically.</summary>");
        sb.AppendLine("    internal static readonly string[] AllScopeNames =");
        sb.AppendLine("    [");
        for (var i = 0; i < scopes.Length; i++)
        {
            var comma = i < scopes.Length - 1 ? "," : "";
            sb.AppendLine($"        \"{scopes[i].Name}\"{comma}");
        }
        sb.AppendLine("    ];");
        sb.AppendLine();

        // AllScopesList pre-formatted string for error messages
        sb.Append("    /// <summary>Pre-formatted list of all scope names for error messages.</summary>");
        sb.AppendLine();
        var quotedNames = scopes.Select(static s => $"\\\"" + s.Name + "\\\"").ToArray();
        sb.AppendLine($"    internal static readonly string AllScopesList = \"{string.Join(", ", scopes.Select(static s => "\\\"" + s.Name + "\\\""))}\";");
        sb.AppendLine();

        // IsKnownScope method — UTF-8 span based for parser hot paths
        sb.AppendLine("    internal static bool IsKnownScope(string name)");
        sb.AppendLine("    {");
        sb.AppendLine("        return name switch");
        sb.AppendLine("        {");
        foreach (var scope in scopes)
        {
            sb.AppendLine($"            \"{scope.Name}\" => true,");
        }
        sb.AppendLine("            _ => false,");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        // GetAllowedValues method — returns allowed values for a scope, or null if unknown
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Returns the allowed permission values for the given scope name,");
        sb.AppendLine("    /// or null if the scope is unknown.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal static string[]? GetAllowedValues(string scopeName)");
        sb.AppendLine("    {");
        sb.AppendLine("        return scopeName switch");
        sb.AppendLine("        {");

        // Group scopes by their allowed values to minimize code duplication
        var groups = scopes.GroupBy(s => string.Join("|", s.Allowed), StringComparer.Ordinal).ToArray();
        foreach (var group in groups)
        {
            var members = group.ToArray();
            var allowedArray = $"[{string.Join(", ", members[0].Allowed.Select(static v => $"\"{v}\""))}]";
            foreach (var m in members)
            {
                sb.AppendLine($"            \"{m.Name}\" => {allowedArray},");
            }
        }

        sb.AppendLine("            _ => null,");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return TextNormalization.NormalizeToLf(sb.ToString());
    }
}
