<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.6" />
    <PackageVersion Include="Microsoft.Playwright" Version="1.59.0" />
    <PackageVersion Include="ConsoleAppFramework" Version="5.7.13" />
    <PackageVersion Include="TUnit" Version="1.12.111" />
    <PackageVersion Include="VYaml" Version="1.2.0" />
  </ItemGroup>
</Project>
