<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Seiton.Update</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ConsoleAppFramework" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Seiton.Update.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
