# Generated by scripts/render-homebrew-seiton-formula.sh — do not hand-edit; release workflow overwrites.
# frozen_string_literal: true

class Seiton < Formula
  desc "Lint GitHub Actions workflows and action metadata files"
  homepage "https://github.com/guitarrapc/seiton"
  version "0.9.28"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/guitarrapc/seiton/releases/download/v0.9.28/seiton-osx-arm64.tar.gz"
      sha256 "cf106b8bbeef76a62eb775c21b42d3b8d44b3cc5373153f6042e7f0133a67b9c"
    elsif Hardware::CPU.intel?
      url "https://github.com/guitarrapc/seiton/releases/download/v0.9.28/seiton-osx-amd64.tar.gz"
      sha256 "6e7ce7c64fcf0967bfd0b9327492dbfd5fd28eb161c9bf6384e02f874c7eea58"
    else
      odie "seiton: unsupported macOS CPU"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guitarrapc/seiton/releases/download/v0.9.28/seiton-linux-arm64.tar.gz"
      sha256 "5fb574c7b838bb2e2337612678b34800bcb222ee8956a33f6e40f317e975ab4a"
    elsif Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guitarrapc/seiton/releases/download/v0.9.28/seiton-linux-amd64.tar.gz"
      sha256 "9fc5ff76eba86b039ac34d8ab425e000d6740633f4ec668d6ea63dcf379ecfe8"
    else
      odie "seiton: unsupported Linux CPU"
    end
  end

  def install
    bin.install "seiton"
  end

  test do
    system "#{bin}/seiton", "version"
  end
end
