# Generated by scripts/render-homebrew-seiton-formula.sh — do not hand-edit; release workflow overwrites.
# frozen_string_literal: true

class Seiton < Formula
  desc "Lint GitHub Actions workflows and action metadata files"
  homepage "https://github.com/guitarrapc/seiton"
  version "0.9.24"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/guitarrapc/seiton/releases/download/v0.9.24/seiton-osx-arm64.tar.gz"
      sha256 "fc355aa97e12a064b06af1d4b076752bb5d80f6b65fc121e85e078a7436d4507"
    elsif Hardware::CPU.intel?
      url "https://github.com/guitarrapc/seiton/releases/download/v0.9.24/seiton-osx-amd64.tar.gz"
      sha256 "0a8f909c7d1be6c537d965c9f4967c49d01dd554044d7ffff6289e069247a200"
    else
      odie "seiton: unsupported macOS CPU"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guitarrapc/seiton/releases/download/v0.9.24/seiton-linux-arm64.tar.gz"
      sha256 "934c87c1cb7ad43bbe8aca984d20eaa156c44d04423e210551ccbd354363c697"
    elsif Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guitarrapc/seiton/releases/download/v0.9.24/seiton-linux-amd64.tar.gz"
      sha256 "1425fcc5dfdd3e94c38555d8c38ea1e3cc6008292c8b98632b148af00eb1cb20"
    else
      odie "seiton: unsupported Linux CPU"
    end
  end

  def install
    bin.install "seiton"
  end

  test do
    system "#{bin}/seiton", "version"
  end
end
