#!/usr/bin/env bash
# Emit Formula/seiton.rb to stdout. POSIX checksums: "HASH  filename" per line.
# Usage: render-homebrew-seiton-formula.sh VERSION TAG OWNER/REPO PATH_TO_checksums-sha256.txt
set -euo pipefail

VERSION="$1"
TAG="$2"
REPO_FULL="$3"
CHECKSUMS="$4"

OWNER="${REPO_FULL%%/*}"
NAME="${REPO_FULL#*/}"

lookup_hash() {
  local art="$1"
  awk -v art="$art" '$2 == art || $2 == "*" art { print $1; exit }' "$CHECKSUMS"
}

H_LINUX_AMD64=$(lookup_hash "seiton-linux-amd64.tar.gz")
H_LINUX_ARM64=$(lookup_hash "seiton-linux-arm64.tar.gz")
H_OSX_AMD64=$(lookup_hash "seiton-osx-amd64.tar.gz")
H_OSX_ARM64=$(lookup_hash "seiton-osx-arm64.tar.gz")

require_hash() {
  local label="$1" val="$2"
  if [ -z "$val" ]; then
    echo "render-homebrew-seiton-formula: missing checksum for ${label} in $CHECKSUMS" >&2
    exit 1
  fi
}

require_hash "seiton-linux-amd64.tar.gz" "$H_LINUX_AMD64"
require_hash "seiton-linux-arm64.tar.gz" "$H_LINUX_ARM64"
require_hash "seiton-osx-amd64.tar.gz" "$H_OSX_AMD64"
require_hash "seiton-osx-arm64.tar.gz" "$H_OSX_ARM64"

BASE="https://github.com/${OWNER}/${NAME}/releases/download/${TAG}"

cat <<EOF
# Generated by scripts/render-homebrew-seiton-formula.sh — do not hand-edit; release workflow overwrites.
# frozen_string_literal: true

class Seiton < Formula
  desc "Lint GitHub Actions workflows and action metadata files"
  homepage "https://github.com/${OWNER}/${NAME}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "${BASE}/seiton-osx-arm64.tar.gz"
      sha256 "${H_OSX_ARM64}"
    elsif Hardware::CPU.intel?
      url "${BASE}/seiton-osx-amd64.tar.gz"
      sha256 "${H_OSX_AMD64}"
    else
      odie "seiton: unsupported macOS CPU"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "${BASE}/seiton-linux-arm64.tar.gz"
      sha256 "${H_LINUX_ARM64}"
    elsif Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "${BASE}/seiton-linux-amd64.tar.gz"
      sha256 "${H_LINUX_AMD64}"
    else
      odie "seiton: unsupported Linux CPU"
    end
  end

  def install
    bin.install "seiton"
  end

  test do
    system "#{bin}/seiton", "version"
  end
end
EOF
