on:
  pull_request:
    branches: [main]
jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: FooBar
        run: echo '${{ env.FOOBAR }}'
        env:
          FOOBAR: "foobar"
