<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Seiton.Core\Seiton.Core.csproj" />
    <ProjectReference Include="..\Seiton.Playground.Core\Seiton.Playground.Core.csproj" />
  </ItemGroup>

</Project>
